language: generic
matrix:
  include:
    - os: osx
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      env: TRAVIS_PYTHON_VERSION=3.5
    - os: osx
      env: TRAVIS_PYTHON_VERSION=3.6
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes -q conda
  - conda config --set anaconda_upload no
  - conda config --add channels conda-forge
  - conda info -a
install:
  - conda create --yes --name build-environment python=$TRAVIS_PYTHON_VERSION
  - source activate build-environment
  - conda install --yes conda-build conda-verify anaconda-client
  - conda build --python $TRAVIS_PYTHON_VERSION camelot-py
script:
  - echo "Removed conda install --use-local camelot-py so can't test camelot --help"
after_success:
  - chmod +x deploy_anaconda.sh
  - ./deploy_anaconda.sh
